name: hagenberg_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  path: ^1.9.0
  http: ^1.2.2
  flutter_svg: ^2.0.10+1
  google_maps_flutter: ^2.7.0
  url_launcher: ^6.3.0
  cloud_firestore: ^5.0.2
  firebase_core: ^3.1.1
  firebase_storage: ^12.1.0
  firebase_database: ^11.0.3
  firebase_auth: ^5.1.2




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/schloss.jpeg
    - assets/hgb_logo.png
    - assets/events_images/yoga.jpeg
    - assets/events_images/hiking.png
    - assets/events_images/gym.jpeg
    - assets/events_images/horse_riding.JPG
    - assets/events_images/karate.jpg
    - assets/events_images/skiing.JPG
    - assets/events_images/swimming.jpeg
    - assets/events_images/tennis.JPEG
    - assets/icons/info_icon.png
    - assets/icons/list_icon.png
    - assets/icons/map_icon.png
    - assets/icons/castle_icon.svg
    - assets/icons/heart_empty_borders_icon.png
    - assets/icons/heart_filled_icon.png
    - assets/icons/heart_favourites_icon.png

  fonts:
    - family: AbrilFatface
      fonts:
        - asset: assets/fonts/AbrilFatface-Regular.ttf
    - family: AbhayaLibre
      fonts:
        - asset: assets/fonts/AbhayaLibre-Regular.ttf

